---
title: "flat_check_data_integrity.Rmd"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(assertthat)
library(dplyr)
```

```{r development-1}
# Load already included functions
pkgload::load_all(export_all = FALSE)
```

# Function check_data_integrity

```{r function-check_data_integrity}
#' check_data_integrity: check dataset integrity
#'
#' @param data a dataset to check
#' @param colname a column to check
#' @return Side effect: a text message if everything is OK
#' @importFrom assertthat assert_that
#' @importFrom dplyr pull
#' @export
#'
#' @examples
check_data_integrity <- function(data, colname) {
  assert_that(is.data.frame(data))
  assert_that({{colname}} %in% names(data), msg = paste({{colname}},"does not exist in data"))
  
  detect_str <- data %>% pull({colname}) %>% 
    stringr::str_detect('\\+')
  assert_that(!any(detect_str, na.rm = T), msg = paste("forbidden pattern detected in",{{colname}}))
  return("Dataset is OK")
}
```

```{r examples-check_data_integrity}
datafile <- system.file("nyc_squirrels_sample.csv", package = "autonomy.ch")
nyc_squirrels <- read.csv(datafile)

check_data_integrity(nyc_squirrels,'primary_fur_color')
#check_data_integrity(nyc_squirrels,'combination_of_primary_and_highlight_color')
```

```{r tests-check_data_integrity}
datafile <- system.file("nyc_squirrels_sample.csv", package = "autonomy.ch")
nyc_squirrels <- read.csv(datafile)
  
colname_ok = 'primary_fur_color'
colname_with_error = 'combination_of_primary_and_highlight_color'

test_that("1a. check_data_integrity checking dataset input", {
  expect_error(check_data_integrity(NULL, colname_ok))
})

test_that("1b. check_data_integrity checking colname input", {
  expect_error(check_data_integrity(nyc_squirrels, 'not_existing_col'))
})

test_that("2. check_data_integrity checking data OK", {
  expect_equal(check_data_integrity(nyc_squirrels, colname_ok),'Dataset is OK')
})

test_that("3. check_data_integrity catching data error", {
  expect_error(check_data_integrity(nyc_squirrels, colname_with_error))
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_check_data_integrity.Rmd", vignette_name = "Get started")
```

