# Generated by fusen: do not edit by hand

test_that("check_data_integrity works", {
  datafile <- system.file("nyc_squirrels_sample.csv", package = "autonomy.ch")
  nyc_squirrels <- read.csv(datafile)
  colname = 'combination_of_primary_and_highlight_color'
  
  testthat::expect_error(check_data_integrity(NULL, colname))
  testthat::expect_error(check_data_integrity(nyc_squirrels, colname))

})
