# Generated by fusen: do not edit by hand

datafile <- system.file("nyc_squirrels_sample.csv", package = "autonomy.ch")
nyc_squirrels <- read.csv(datafile)
  
colname_ok = 'primary_fur_color'
colname_with_error = 'combination_of_primary_and_highlight_color'

test_that("1a. check_data_integrity checking dataset input", {
  expect_error(check_data_integrity(NULL, colname_ok))
})

test_that("1b. check_data_integrity checking colname input", {
  expect_error(check_data_integrity(nyc_squirrels, 'not_existing_col'))
})

test_that("2. check_data_integrity checking data OK", {
  expect_equal(check_data_integrity(nyc_squirrels, colname_ok),'Dataset is OK')
})

test_that("3. check_data_integrity catching data error", {
  expect_error(check_data_integrity(nyc_squirrels, colname_with_error))
})
