# Generated by fusen: do not edit by hand

#' check_data_integrity check dataset integrity
#'
#' @param data a dataset to check
#' @param colname a column to check
#' @return Side effect: a text message if everything is OK
#' @importFrom assertthat assert_that
#' @importFrom dplyr pull
#' @export
#'
#' @examples
#' datafile <- system.file("nyc_squirrels_sample.csv", package = "autonomy.ch")
#' nyc_squirrels <- read.csv(datafile)
#' 
#' check_data_integrity(nyc_squirrels,'primary_fur_color')
#' #check_data_integrity(nyc_squirrels,'combination_of_primary_and_highlight_color')
check_data_integrity <- function(data, colname) {
  assert_that(is.data.frame(data))
  assert_that({{colname}} %in% names(data))
  
  detect_str <- data %>% pull({colname}) %>% 
    stringr::str_detect('\\+')
  assert_that(!any(detect_str, na.rm = T))
  return("Dataset is OK")
}
